import { motion } from 'framer-motion';
import { Link } from 'wouter';
import { ArrowLeft, Sparkles, Eye, Flame } from 'lucide-react';
import { Button } from '@/components/ui/button';

export function About() {
  const fadeIn = {
    initial: { opacity: 0, y: 20 },
    animate: { opacity: 1, y: 0 },
    transition: { duration: 0.6 }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-[#1a0f0a] via-[#2a1a10] to-[#1a0f0a] text-[#ffddaa] font-cinzel">
      <div className="max-w-4xl mx-auto px-6 py-12">
        <Link href="/">
          <Button variant="ghost" className="mb-8 text-[#ffaa55] hover:text-white hover:bg-white/10">
            <ArrowLeft className="w-4 h-4 mr-2" /> Return to the Playa
          </Button>
        </Link>

        <motion.header {...fadeIn} className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-bold text-[#ffaa55] tracking-widest mb-4">
            THE PLAYA ARTIFACTS
          </h1>
          <div className="w-32 h-[2px] bg-gradient-to-r from-transparent via-[#ffaa55] to-transparent mx-auto mb-6"></div>
          <p className="text-xl text-[#ccaa88] font-rajdhani max-w-2xl mx-auto">
            Three interactive art installations powered by artificial intelligence, designed to catalyze serendipity, reflection, and transformation on the Playa.
          </p>
        </motion.header>

        <div className="space-y-16">
          <motion.section 
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2, duration: 0.6 }}
            className="bg-gradient-to-r from-[#3e2723]/50 to-transparent p-8 rounded-lg border-l-4 border-[#ffaa55]"
          >
            <div className="flex items-start gap-6">
              <div className="p-4 bg-[#ffaa55]/20 rounded-full">
                <Sparkles className="w-8 h-8 text-[#ffaa55]" />
              </div>
              <div>
                <h2 className="text-2xl md:text-3xl font-bold text-[#ffaa55] mb-2 tracking-wider">
                  THE SERENDIPITY DISPENSER
                </h2>
                <p className="text-sm text-[#8d6e63] uppercase tracking-widest mb-4">Future • Action • Possibility</p>
                <div className="space-y-4 font-rajdhani text-lg leading-relaxed">
                  <p>
                    A towering obelisk wrapped in sacred geometry, pulsing with golden light. The Dispenser is a catalyst for the unexpected—a machine that transforms intention into adventure.
                  </p>
                  <p>
                    Approach the artifact, offer your aspiration, and receive a unique mission generated by AI. Each directive is crafted in real-time, calibrated to your desired level of intensity, social engagement, and absurdity.
                  </p>
                  <p className="text-[#ffaa55] italic">
                    "Serendipity is not random. It is the universe responding to your openness."
                  </p>
                </div>
                <div className="mt-6 p-4 bg-black/30 rounded border border-[#ffaa55]/20">
                  <h4 className="text-sm text-[#ffaa55] uppercase tracking-widest mb-2">How It Works</h4>
                  <ul className="list-disc list-inside text-sm font-rajdhani text-[#ccaa88] space-y-1">
                    <li>Click the golden obelisk to begin</li>
                    <li>Enter what you seek or wish to experience</li>
                    <li>Adjust the calibration sliders (optional)</li>
                    <li>Receive your AI-generated mission on a sacred token</li>
                  </ul>
                </div>
              </div>
            </div>
          </motion.section>

          <motion.section 
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.4, duration: 0.6 }}
            className="bg-gradient-to-l from-[#004d5e]/30 to-transparent p-8 rounded-lg border-r-4 border-cyan-400"
          >
            <div className="flex items-start gap-6 flex-row-reverse text-right">
              <div className="p-4 bg-cyan-400/20 rounded-full">
                <Eye className="w-8 h-8 text-cyan-400" />
              </div>
              <div>
                <h2 className="text-2xl md:text-3xl font-bold text-cyan-400 mb-2 tracking-wider">
                  THE REFLECTIVE ORACLE
                </h2>
                <p className="text-sm text-cyan-700 uppercase tracking-widest mb-4">Present • Self • Clarity</p>
                <div className="space-y-4 font-rajdhani text-lg leading-relaxed text-left">
                  <p>
                    A floating chrome cube, impossibly reflective, rotating slowly in the desert air. The Oracle does not give answers—it asks questions that you didn't know you needed to hear.
                  </p>
                  <p>
                    Engage in a dialogue with the mirror. Speak your thoughts, and the AI will respond not with solutions, but with reflections that cut to the heart of your assumptions and desires.
                  </p>
                  <p className="text-cyan-400 italic">
                    "The mirror shows only what you bring to it. Look closer."
                  </p>
                </div>
                <div className="mt-6 p-4 bg-black/30 rounded border border-cyan-400/20 text-left">
                  <h4 className="text-sm text-cyan-400 uppercase tracking-widest mb-2">How It Works</h4>
                  <ul className="list-disc list-inside text-sm font-rajdhani text-[#ccaa88] space-y-1">
                    <li>Click the reflective cube to begin</li>
                    <li>Share your thoughts, feelings, or questions</li>
                    <li>Receive a thought-provoking question in return</li>
                    <li>Continue the dialogue as long as you wish</li>
                  </ul>
                </div>
              </div>
            </div>
          </motion.section>

          <motion.section 
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.6, duration: 0.6 }}
            className="bg-gradient-to-r from-[#5d1a1a]/30 to-transparent p-8 rounded-lg border-l-4 border-orange-500"
          >
            <div className="flex items-start gap-6">
              <div className="p-4 bg-orange-500/20 rounded-full">
                <Flame className="w-8 h-8 text-orange-500" />
              </div>
              <div>
                <h2 className="text-2xl md:text-3xl font-bold text-orange-500 mb-2 tracking-wider">
                  THE TEMPLE OF TRANSMUTATION
                </h2>
                <p className="text-sm text-orange-800 uppercase tracking-widest mb-4">Past • Release • Alchemy</p>
                <div className="space-y-4 font-rajdhani text-lg leading-relaxed">
                  <p>
                    A sacred geometry lantern of golden light, its rings spinning like the orbits of celestial bodies. The Temple is not about destruction—it is about transformation.
                  </p>
                  <p>
                    Offer your burden to the fire. The AI will acknowledge your weight with compassion, then transmute it into wisdom. Your fear becomes curiosity. Your anger becomes passion. Your sorrow becomes depth.
                  </p>
                  <p className="text-orange-400 italic">
                    "The fire does not destroy. It reveals what was gold all along."
                  </p>
                </div>
                <div className="mt-6 p-4 bg-black/30 rounded border border-orange-500/20">
                  <h4 className="text-sm text-orange-500 uppercase tracking-widest mb-2">How It Works</h4>
                  <ul className="list-disc list-inside text-sm font-rajdhani text-[#ccaa88] space-y-1">
                    <li>Click the golden lantern to enter</li>
                    <li>Write down what you wish to release</li>
                    <li>Watch as it is transmuted in the alchemical fire</li>
                    <li>Receive wisdom that reframes your burden as strength</li>
                  </ul>
                </div>
              </div>
            </div>
          </motion.section>
        </div>

        <motion.footer 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.8, duration: 0.6 }}
          className="mt-20 text-center border-t border-[#ffaa55]/20 pt-12"
        >
          <h3 className="text-2xl font-bold text-[#ffaa55] mb-4">THE 10 PRINCIPLES</h3>
          <p className="text-[#ccaa88] font-rajdhani mb-8 max-w-2xl mx-auto">
            These installations are inspired by and aligned with the 10 Principles of Burning Man: 
            Radical Inclusion, Gifting, Decommodification, Radical Self-reliance, Radical Self-expression, 
            Communal Effort, Civic Responsibility, Leaving No Trace, Participation, and Immediacy.
          </p>
          
          <div className="p-6 bg-[#3e2723]/30 rounded-lg border border-[#ffaa55]/10 max-w-xl mx-auto">
            <p className="text-sm text-[#8d6e63] uppercase tracking-widest mb-2">Powered By</p>
            <p className="text-[#ffaa55] font-bold">Claude AI</p>
            <p className="text-xs text-[#8d6e63] mt-2 font-rajdhani">
              Each interaction is uniquely generated by artificial intelligence, 
              ensuring no two experiences are ever the same.
            </p>
          </div>

          <div className="mt-12">
            <Link href="/">
              <Button className="bg-[#ffaa55] hover:bg-[#ffcc00] text-[#1a0f0a] font-cinzel tracking-widest px-8 py-6 text-lg">
                ENTER THE EXPERIENCE
              </Button>
            </Link>
          </div>
        </motion.footer>
      </div>
    </div>
  );
}
