import { useState, useEffect } from 'react';
import { useStore } from '../store';
import { motion, AnimatePresence } from 'framer-motion';
import { Volume2, VolumeX, HelpCircle, X, Download, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';

export function Interface() {
  const { 
    isNearMachine, 
    isInputOpen, 
    setInputOpen, 
    startProcessing, 
    processingStep, 
    mission, 
    reset, 
    audioEnabled, 
    toggleAudio, 
    isHelpOpen, 
    toggleHelp 
  } = useStore();

  const [aspiration, setAspiration] = useState('');

  const handleSubmit = () => {
    if (aspiration.trim()) {
      startProcessing(aspiration);
    }
  };

  const handleDownload = () => {
    if (!mission) return;
    const text = `AI SERENDIPITY MISSION\n\nTitle: ${mission.title}\nCategory: ${mission.category}\n\nMission: ${mission.description}\n\nGenerated by the Oracle.`;
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `serendipity-mission-${mission.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="absolute inset-0 pointer-events-none">
      {/* HUD Header */}
      <header className="absolute top-0 left-0 w-full p-6 flex justify-between items-start pointer-events-auto z-50">
        <div className="backdrop-blur-sm bg-black/20 p-2 rounded border border-white/10">
          <h1 className="text-2xl font-bold text-white tracking-widest text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500">
            SERENDIPITY ORACLE
          </h1>
          <p className="text-xs text-cyan-200/60 font-mono">SYS.VER.3.0 // ONLINE</p>
        </div>

        <div className="flex gap-2">
          <Button variant="outline" size="icon" onClick={toggleAudio} className="bg-black/40 border-cyan-500/30 text-cyan-400 hover:bg-cyan-900/20 hover:text-cyan-200">
            {audioEnabled ? <Volume2 className="h-4 w-4" /> : <VolumeX className="h-4 w-4" />}
          </Button>
          <Button variant="outline" size="icon" onClick={toggleHelp} className="bg-black/40 border-cyan-500/30 text-cyan-400 hover:bg-cyan-900/20 hover:text-cyan-200">
            <HelpCircle className="h-4 w-4" />
          </Button>
        </div>
      </header>

      {/* Input Modal */}
      <Dialog open={isInputOpen} onOpenChange={setInputOpen}>
        <DialogContent className="bg-black/90 border-cyan-500/50 text-white sm:max-w-[425px] pointer-events-auto backdrop-blur-xl">
          <DialogHeader>
            <DialogTitle className="text-cyan-400 font-orbitron tracking-wider">COMMUNE WITH THE ORACLE</DialogTitle>
            <DialogDescription className="text-cyan-100/60 font-rajdhani">
              State your current aspiration, desire, or question. The machine will weave a path for you.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <Textarea 
              placeholder="I seek to find beauty in the mundane..." 
              value={aspiration}
              onChange={(e) => setAspiration(e.target.value)}
              className="bg-black/50 border-cyan-800 focus:border-cyan-400 text-cyan-100 font-rajdhani h-32 resize-none"
              maxLength={150}
            />
            <div className="flex justify-between items-center text-xs text-cyan-500/50">
                <span>{aspiration.length}/150 CHARS</span>
                <span>NEURAL LINK ACTIVE</span>
            </div>
          </div>
          <div className="flex justify-end">
            <Button 
                onClick={handleSubmit} 
                disabled={!aspiration.trim()}
                className="bg-cyan-600 hover:bg-cyan-500 text-white font-orbitron tracking-widest border border-cyan-400 shadow-[0_0_15px_rgba(0,255,255,0.3)]"
            >
              INITIATE SEQUENCE
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Processing Overlay */}
      <AnimatePresence>
        {processingStep && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 flex items-center justify-center bg-black/60 backdrop-blur-sm z-40"
          >
            <div className="text-center">
                <div className="w-16 h-16 border-4 border-t-cyan-400 border-r-transparent border-b-cyan-400 border-l-transparent rounded-full animate-spin mx-auto mb-4"></div>
                <motion.h2 
                    key={processingStep}
                    initial={{ y: 10, opacity: 0 }}
                    animate={{ y: 0, opacity: 1 }}
                    exit={{ y: -10, opacity: 0 }}
                    className="text-2xl text-cyan-400 font-orbitron tracking-widest"
                >
                    {processingStep}
                </motion.h2>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Mission Result Card */}
      <AnimatePresence>
        {mission && (
          <motion.div 
            initial={{ scale: 0.9, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.9, opacity: 0, y: 20 }}
            className="absolute inset-0 flex items-center justify-center z-50 p-4 pointer-events-auto"
          >
            <Card className="w-full max-w-md bg-black/80 border-2 text-white backdrop-blur-xl shadow-[0_0_50px_rgba(0,0,0,0.8)]" style={{ borderColor: mission.color }}>
                <CardHeader className="border-b border-white/10 pb-4">
                    <div className="flex justify-between items-center">
                        <div className="px-2 py-1 rounded text-xs font-bold uppercase tracking-widest text-black" style={{ backgroundColor: mission.color }}>
                            {mission.category}
                        </div>
                        <Button variant="ghost" size="icon" onClick={reset} className="text-white/50 hover:text-white">
                            <X className="h-4 w-4" />
                        </Button>
                    </div>
                    <CardTitle className="text-3xl font-orbitron mt-4 text-transparent bg-clip-text bg-gradient-to-br from-white to-white/50">
                        {mission.title}
                    </CardTitle>
                </CardHeader>
                <CardContent className="pt-6 space-y-6">
                    <p className="text-lg font-rajdhani leading-relaxed text-gray-200">
                        {mission.description}
                    </p>
                    
                    <div className="flex gap-3 pt-4 border-t border-white/10">
                        <Button onClick={handleDownload} className="flex-1 bg-white/10 hover:bg-white/20 border border-white/20 text-white">
                            <Download className="mr-2 h-4 w-4" /> SAVE MISSION
                        </Button>
                        <Button onClick={reset} className="flex-1 bg-transparent hover:bg-white/5 border border-white/20 text-white/70">
                            <RefreshCw className="mr-2 h-4 w-4" /> NEW SEARCH
                        </Button>
                    </div>
                </CardContent>
            </Card>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Help Overlay */}
      <Dialog open={isHelpOpen} onOpenChange={toggleHelp}>
        <DialogContent className="bg-black/95 border-cyan-900 text-white pointer-events-auto">
            <DialogHeader>
                <DialogTitle className="font-orbitron text-cyan-400">OPERATIONAL GUIDE</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 font-rajdhani text-lg">
                <p>1. Drag to explore the desert environment.</p>
                <p>2. Click the Floating Monolith to commune with the Oracle.</p>
                <p>3. Offer your aspiration to the machine.</p>
                <p>4. Receive a Serendipity Mission to perform in the real world.</p>
                <div className="pt-4 text-sm text-cyan-500/60 font-mono">
                    WARNING: Missions may cause unexpected joy.
                </div>
            </div>
        </DialogContent>
      </Dialog>

      {/* Footer Hint */}
      {!isNearMachine && !mission && (
        <div className="absolute bottom-8 left-0 w-full text-center pointer-events-none">
            <p className="text-cyan-200/50 font-orbitron tracking-[0.2em] text-sm animate-pulse">
                APPROACH THE MACHINE
            </p>
        </div>
      )}
    </div>
  );
}
